"""add_employment_info_fields

Revision ID: 115e20ee56d6
Revises: febe15bdb8f2
Create Date: 2024-11-26 20:07:29.990335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115e20ee56d6'
down_revision = 'febe15bdb8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfc_empresa', sa.String(length=13), nullable=False))
        batch_op.add_column(sa.Column('extension', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('horario', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('nrp', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('ingresos_adicionales', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('empresa_colonia', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('empresa_estado', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('empresa_codigo_postal', sa.String(length=10), nullable=False))
        batch_op.alter_column('antiguedad',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('ingreso_mensual',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('email_empresa',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('email_empresa',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('ingreso_mensual',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('antiguedad',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('empresa_codigo_postal')
        batch_op.drop_column('empresa_estado')
        batch_op.drop_column('empresa_colonia')
        batch_op.drop_column('ingresos_adicionales')
        batch_op.drop_column('nrp')
        batch_op.drop_column('horario')
        batch_op.drop_column('url')
        batch_op.drop_column('extension')
        batch_op.drop_column('rfc_empresa')

    # ### end Alembic commands ###
