"""Add new client fields with sections

Revision ID: 2b0e76206929
Revises: 9686c60206e7
Create Date: 2024-11-26 17:09:13.860333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0e76206929'
down_revision = '9686c60206e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('lugar_nacimiento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nacionalidad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estado_civil', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('rfc', sa.String(length=13), nullable=True))
        batch_op.add_column(sa.Column('curp', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('nombre_empresa', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('puesto', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('antiguedad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ingreso_mensual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('direccion_empresa', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefono_empresa', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_empresa', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ref1_nombre', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ref1_telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ref1_relacion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ref2_nombre', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ref2_telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ref2_relacion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('conyuge_nombre', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('conyuge_apellido_paterno', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('conyuge_apellido_materno', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('conyuge_fecha_nacimiento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('conyuge_rfc', sa.String(length=13), nullable=True))
        batch_op.add_column(sa.Column('conyuge_curp', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('conyuge_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('conyuge_telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('conyuge_celular', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('conyuge_nombre_empresa', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('conyuge_puesto', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('conyuge_antiguedad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('conyuge_ingreso_mensual', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('conyuge_ingreso_mensual')
        batch_op.drop_column('conyuge_antiguedad')
        batch_op.drop_column('conyuge_puesto')
        batch_op.drop_column('conyuge_nombre_empresa')
        batch_op.drop_column('conyuge_celular')
        batch_op.drop_column('conyuge_telefono')
        batch_op.drop_column('conyuge_email')
        batch_op.drop_column('conyuge_curp')
        batch_op.drop_column('conyuge_rfc')
        batch_op.drop_column('conyuge_fecha_nacimiento')
        batch_op.drop_column('conyuge_apellido_materno')
        batch_op.drop_column('conyuge_apellido_paterno')
        batch_op.drop_column('conyuge_nombre')
        batch_op.drop_column('ref2_relacion')
        batch_op.drop_column('ref2_telefono')
        batch_op.drop_column('ref2_nombre')
        batch_op.drop_column('ref1_relacion')
        batch_op.drop_column('ref1_telefono')
        batch_op.drop_column('ref1_nombre')
        batch_op.drop_column('sector')
        batch_op.drop_column('email_empresa')
        batch_op.drop_column('telefono_empresa')
        batch_op.drop_column('direccion_empresa')
        batch_op.drop_column('ingreso_mensual')
        batch_op.drop_column('antiguedad')
        batch_op.drop_column('puesto')
        batch_op.drop_column('nombre_empresa')
        batch_op.drop_column('curp')
        batch_op.drop_column('rfc')
        batch_op.drop_column('estado_civil')
        batch_op.drop_column('nacionalidad')
        batch_op.drop_column('lugar_nacimiento')
        batch_op.drop_column('fecha_nacimiento')

    # ### end Alembic commands ###
