"""update reference fields

Revision ID: 310df0b6d6c1
Revises: 5731c91e46ca
Create Date: 2024-11-26 20:39:57.744238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310df0b6d6c1'
down_revision = '5731c91e46ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido_paterno_referencia_1', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('apellido_materno_referencia_1', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('telefono_celular_referencia_1', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('direccion_referencia_1', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('estado_referencia_1', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('colonia_referencia_1', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('entidad_referencia_1', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('municipio_referencia_1', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('codigo_postal_referencia_1', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('apellido_paterno_referencia_2', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('apellido_materno_referencia_2', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('telefono_celular_referencia_2', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('direccion_referencia_2', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('estado_referencia_2', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('colonia_referencia_2', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('entidad_referencia_2', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('municipio_referencia_2', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('codigo_postal_referencia_2', sa.String(length=10), nullable=False))
        batch_op.alter_column('ref1_nombre',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('ref2_nombre',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('ref1_telefono')
        batch_op.drop_column('ref2_telefono')
        batch_op.drop_column('ref1_relacion')
        batch_op.drop_column('ref2_relacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref2_relacion', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('ref1_relacion', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('ref2_telefono', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('ref1_telefono', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('ref2_nombre',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('ref1_nombre',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('codigo_postal_referencia_2')
        batch_op.drop_column('municipio_referencia_2')
        batch_op.drop_column('entidad_referencia_2')
        batch_op.drop_column('colonia_referencia_2')
        batch_op.drop_column('estado_referencia_2')
        batch_op.drop_column('direccion_referencia_2')
        batch_op.drop_column('telefono_celular_referencia_2')
        batch_op.drop_column('apellido_materno_referencia_2')
        batch_op.drop_column('apellido_paterno_referencia_2')
        batch_op.drop_column('codigo_postal_referencia_1')
        batch_op.drop_column('municipio_referencia_1')
        batch_op.drop_column('entidad_referencia_1')
        batch_op.drop_column('colonia_referencia_1')
        batch_op.drop_column('estado_referencia_1')
        batch_op.drop_column('direccion_referencia_1')
        batch_op.drop_column('telefono_celular_referencia_1')
        batch_op.drop_column('apellido_materno_referencia_1')
        batch_op.drop_column('apellido_paterno_referencia_1')

    # ### end Alembic commands ###
