"""Add colindancia fields to Lote model

Revision ID: 4d69ac5b8ea7
Revises: 7ca094dfe2ac
Create Date: 2024-11-27 03:05:38.743617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d69ac5b8ea7'
down_revision = '7ca094dfe2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colindancia_1', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('colindancia_2', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('colindancia_3', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('colindancia_4', sa.String(length=100), nullable=False))
        batch_op.alter_column('manzana',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('lote',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('estado_del_inmueble',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('orientacion_1',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('orientacion_2',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('orientacion_3',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('orientacion_4',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.alter_column('orientacion_4',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('orientacion_3',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('orientacion_2',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('orientacion_1',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('estado_del_inmueble',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('lote',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('manzana',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('colindancia_4')
        batch_op.drop_column('colindancia_3')
        batch_op.drop_column('colindancia_2')
        batch_op.drop_column('colindancia_1')

    # ### end Alembic commands ###
