"""Add sembrado field to Fraccionamiento

Revision ID: 4fca74ffaffe
Revises: d1d5b6d2855a
Create Date: 2024-11-27 02:36:16.414835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fca74ffaffe'
down_revision = 'd1d5b6d2855a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraccionamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('sembrado', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paquetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fraccionamiento_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fraccionamiento_id'], ['fraccionamiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paquete_id', sa.Integer(), nullable=False),
    sa.Column('prototipo_id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=100), nullable=False),
    sa.Column('numero_exterior', sa.Integer(), nullable=False),
    sa.Column('numero_interior', sa.Integer(), nullable=False),
    sa.Column('manzana', sa.String(length=20), nullable=False),
    sa.Column('lote', sa.String(length=20), nullable=False),
    sa.Column('cuv', sa.String(length=50), nullable=False),
    sa.Column('terreno', sa.Float(), nullable=False),
    sa.Column('tipo_de_lote', sa.String(length=50), nullable=False),
    sa.Column('estado_del_inmueble', sa.String(length=20), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('orientacion_1', sa.String(length=20), nullable=False),
    sa.Column('medidas_orientacion_1', sa.String(length=50), nullable=False),
    sa.Column('orientacion_2', sa.String(length=20), nullable=False),
    sa.Column('medidas_orientacion_2', sa.String(length=50), nullable=False),
    sa.Column('orientacion_3', sa.String(length=20), nullable=False),
    sa.Column('medidas_orientacion_3', sa.String(length=50), nullable=False),
    sa.Column('orientacion_4', sa.String(length=20), nullable=False),
    sa.Column('medidas_orientacion_4', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paquete_id'], ['paquetes.id'], ),
    sa.ForeignKeyConstraint(['prototipo_id'], ['prototipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lotes')
    op.drop_table('paquetes')
    op.drop_table('fraccionamiento')
    # ### end Alembic commands ###
