"""update phone field to exactly 10 digits

Revision ID: 5731c91e46ca
Revises: bd10f42038a7
Create Date: 2024-11-26 20:26:01.954616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5731c91e46ca'
down_revision = 'bd10f42038a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
