"""Make ubicacion optional in Fraccionamiento

Revision ID: 7ca094dfe2ac
Revises: 4fca74ffaffe
Create Date: 2024-11-27 02:48:49.398564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca094dfe2ac'
down_revision = '4fca74ffaffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fraccionamiento', schema=None) as batch_op:
        batch_op.alter_column('ubicacion',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fraccionamiento', schema=None) as batch_op:
        batch_op.alter_column('ubicacion',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
