"""add credit type and bank fields

Revision ID: 8092a7ac2949
Revises: 310df0b6d6c1
Create Date: 2024-11-26 21:05:59.653571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8092a7ac2949'
down_revision = '310df0b6d6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_de_credito', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('banco', sa.String(length=50), nullable=True))
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('estado_civil',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('estado_civil',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('banco')
        batch_op.drop_column('tipo_de_credito')

    # ### end Alembic commands ###
