"""Make fields optional in Lote model

Revision ID: 838a46888a5a
Revises: 4d69ac5b8ea7
Create Date: 2024-11-27 03:09:41.248716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838a46888a5a'
down_revision = '4d69ac5b8ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.alter_column('numero_interior',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cuv',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('terreno',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('orientacion_1',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('medidas_orientacion_1',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('colindancia_1',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('orientacion_2',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('medidas_orientacion_2',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('colindancia_2',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('orientacion_3',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('medidas_orientacion_3',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('colindancia_3',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('orientacion_4',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('medidas_orientacion_4',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('colindancia_4',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.alter_column('colindancia_4',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('medidas_orientacion_4',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('orientacion_4',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('colindancia_3',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('medidas_orientacion_3',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('orientacion_3',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('colindancia_2',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('medidas_orientacion_2',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('orientacion_2',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('colindancia_1',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('medidas_orientacion_1',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('orientacion_1',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('terreno',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('cuv',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('numero_interior',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
