"""Add Prototipo models and preserve existing tables

Revision ID: 8e2b7cb3321c
Revises: a151e71e415f
Create Date: 2024-11-27 00:04:56.422619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2b7cb3321c'
down_revision = 'a151e71e415f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=64), nullable=False),
    sa.Column('apellido_materno', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('regimen_matrimonial', sa.String(length=50), nullable=True),
    sa.Column('nacionalidad', sa.String(length=50), nullable=True),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('curp', sa.String(length=18), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('tipo_de_credito', sa.String(length=50), nullable=True),
    sa.Column('banco', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('colonia', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=64), nullable=True),
    sa.Column('estado', sa.String(length=64), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('como_se_entero', sa.String(length=50), nullable=True),
    sa.Column('nombre_empresa', sa.String(length=100), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=True),
    sa.Column('antiguedad', sa.String(length=50), nullable=True),
    sa.Column('direccion_empresa', sa.String(length=200), nullable=True),
    sa.Column('email_empresa', sa.String(length=100), nullable=True),
    sa.Column('rfc_empresa', sa.String(length=13), nullable=True),
    sa.Column('nrp', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('horario', sa.String(length=100), nullable=True),
    sa.Column('ingreso_mensual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ingresos_adicionales', sa.String(length=200), nullable=True),
    sa.Column('empresa_colonia', sa.String(length=100), nullable=True),
    sa.Column('empresa_estado', sa.String(length=50), nullable=True),
    sa.Column('empresa_codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('ref1_nombre', sa.String(length=200), nullable=True),
    sa.Column('apellido_paterno_referencia_1', sa.String(length=100), nullable=True),
    sa.Column('apellido_materno_referencia_1', sa.String(length=100), nullable=True),
    sa.Column('telefono_celular_referencia_1', sa.String(length=10), nullable=True),
    sa.Column('direccion_referencia_1', sa.String(length=200), nullable=True),
    sa.Column('estado_referencia_1', sa.String(length=64), nullable=True),
    sa.Column('colonia_referencia_1', sa.String(length=100), nullable=True),
    sa.Column('entidad_referencia_1', sa.String(length=64), nullable=True),
    sa.Column('municipio_referencia_1', sa.String(length=64), nullable=True),
    sa.Column('codigo_postal_referencia_1', sa.String(length=10), nullable=True),
    sa.Column('ref2_nombre', sa.String(length=200), nullable=True),
    sa.Column('apellido_paterno_referencia_2', sa.String(length=100), nullable=True),
    sa.Column('apellido_materno_referencia_2', sa.String(length=100), nullable=True),
    sa.Column('telefono_celular_referencia_2', sa.String(length=10), nullable=True),
    sa.Column('direccion_referencia_2', sa.String(length=200), nullable=True),
    sa.Column('estado_referencia_2', sa.String(length=64), nullable=True),
    sa.Column('colonia_referencia_2', sa.String(length=100), nullable=True),
    sa.Column('entidad_referencia_2', sa.String(length=64), nullable=True),
    sa.Column('municipio_referencia_2', sa.String(length=64), nullable=True),
    sa.Column('codigo_postal_referencia_2', sa.String(length=10), nullable=True),
    sa.Column('conyuge_nombre', sa.String(length=64), nullable=True),
    sa.Column('conyuge_apellido_paterno', sa.String(length=64), nullable=True),
    sa.Column('conyuge_apellido_materno', sa.String(length=64), nullable=True),
    sa.Column('conyuge_fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('conyuge_rfc', sa.String(length=13), nullable=True),
    sa.Column('conyuge_curp', sa.String(length=18), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('notas_seguimiento', sa.Text(), server_default='', nullable=True),
    sa.Column('fecha_ultimo_contacto', sa.Date(), nullable=True),
    sa.Column('fecha_siguiente_contacto', sa.Date(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('conyuge_nombre_empresa', sa.String(length=100), nullable=True),
    sa.Column('conyuge_puesto', sa.String(length=100), nullable=True),
    sa.Column('conyuge_antiguedad', sa.Integer(), nullable=True),
    sa.Column('conyuge_ingreso_mensual', sa.Float(), nullable=True),
    sa.Column('conyuge_email', sa.String(length=120), nullable=True),
    sa.Column('conyuge_telefono', sa.String(length=20), nullable=True),
    sa.Column('conyuge_celular', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_leader_assignments',
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('leader_id', 'user_id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.drop_table('team_leader_assignments')
    op.drop_table('client')
    op.drop_table('user')
    # ### end Alembic commands ###
