"""Remove unused client fields

Revision ID: 9686c60206e7
Revises: 477a61aa27e6
Create Date: 2024-11-26 17:08:07.270188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9686c60206e7'
down_revision = '477a61aa27e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('presupuesto_min')
        batch_op.drop_column('zona_interes')
        batch_op.drop_column('tipo')
        batch_op.drop_column('presupuesto_max')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presupuesto_max', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('zona_interes', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('presupuesto_min', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
