"""Add name fields to user model

Revision ID: a0a7bae2b693
Revises: 1a02e07bf6f7
Create Date: 2024-11-26 13:47:26.218929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a7bae2b693'
down_revision = '1a02e07bf6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('apellido_paterno', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('apellido_materno', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('apellido_materno')
        batch_op.drop_column('apellido_paterno')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
