"""Add Prototipo and PrototipoImagen models

Revision ID: a151e71e415f
Revises: f21f4e84adf2
Create Date: 2024-11-26 23:46:02.946416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a151e71e415f'
down_revision = 'f21f4e84adf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prototipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_prototipo', sa.String(length=100), nullable=False),
    sa.Column('superficie_terreno', sa.Float(), nullable=False),
    sa.Column('superficie_construccion', sa.Float(), nullable=False),
    sa.Column('niveles', sa.Integer(), nullable=False),
    sa.Column('recamaras', sa.Integer(), nullable=False),
    sa.Column('banos', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prototipo_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prototipo_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prototipo_id'], ['prototipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('team_leader_assignments')
    op.drop_table('client')
    op.drop_table('document')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=200), nullable=False),
    sa.Column('upload_date', sa.DATETIME(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=10), nullable=True),
    sa.Column('celular', sa.VARCHAR(length=20), nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ciudad', sa.VARCHAR(length=64), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=64), nullable=True),
    sa.Column('codigo_postal', sa.VARCHAR(length=10), nullable=True),
    sa.Column('fecha_registro', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notas', sa.TEXT(), nullable=True),
    sa.Column('estatus', sa.VARCHAR(length=50), server_default=sa.text("'nuevo'"), nullable=True),
    sa.Column('fecha_nacimiento', sa.DATE(), nullable=True),
    sa.Column('nacionalidad', sa.VARCHAR(length=50), nullable=True),
    sa.Column('estado_civil', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rfc', sa.VARCHAR(length=13), nullable=True),
    sa.Column('curp', sa.VARCHAR(length=18), nullable=True),
    sa.Column('nombre_empresa', sa.VARCHAR(length=100), nullable=True),
    sa.Column('puesto', sa.VARCHAR(length=100), nullable=True),
    sa.Column('antiguedad', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ingreso_mensual', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('direccion_empresa', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email_empresa', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ref1_nombre', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ref2_nombre', sa.VARCHAR(length=200), nullable=True),
    sa.Column('conyuge_nombre', sa.VARCHAR(length=64), nullable=True),
    sa.Column('conyuge_apellido_paterno', sa.VARCHAR(length=64), nullable=True),
    sa.Column('conyuge_apellido_materno', sa.VARCHAR(length=64), nullable=True),
    sa.Column('conyuge_fecha_nacimiento', sa.DATE(), nullable=True),
    sa.Column('conyuge_rfc', sa.VARCHAR(length=13), nullable=True),
    sa.Column('conyuge_curp', sa.VARCHAR(length=18), nullable=True),
    sa.Column('conyuge_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('conyuge_telefono', sa.VARCHAR(length=20), nullable=True),
    sa.Column('conyuge_celular', sa.VARCHAR(length=20), nullable=True),
    sa.Column('conyuge_nombre_empresa', sa.VARCHAR(length=100), nullable=True),
    sa.Column('conyuge_puesto', sa.VARCHAR(length=100), nullable=True),
    sa.Column('conyuge_antiguedad', sa.INTEGER(), nullable=True),
    sa.Column('conyuge_ingreso_mensual', sa.FLOAT(), nullable=True),
    sa.Column('sexo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('regimen_matrimonial', sa.VARCHAR(length=50), nullable=True),
    sa.Column('colonia', sa.VARCHAR(length=100), nullable=True),
    sa.Column('como_se_entero', sa.VARCHAR(length=50), nullable=True),
    sa.Column('apellido_paterno', sa.VARCHAR(length=100), nullable=False),
    sa.Column('apellido_materno', sa.VARCHAR(length=100), nullable=False),
    sa.Column('rfc_empresa', sa.VARCHAR(length=13), nullable=True),
    sa.Column('extension', sa.VARCHAR(length=10), nullable=True),
    sa.Column('url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('horario', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nrp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ingresos_adicionales', sa.VARCHAR(length=200), nullable=True),
    sa.Column('empresa_colonia', sa.VARCHAR(length=100), nullable=True),
    sa.Column('empresa_estado', sa.VARCHAR(length=50), nullable=True),
    sa.Column('empresa_codigo_postal', sa.VARCHAR(length=10), nullable=True),
    sa.Column('apellido_paterno_referencia_1', sa.VARCHAR(length=100), nullable=True),
    sa.Column('apellido_materno_referencia_1', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telefono_celular_referencia_1', sa.VARCHAR(length=10), nullable=True),
    sa.Column('direccion_referencia_1', sa.VARCHAR(length=200), nullable=True),
    sa.Column('estado_referencia_1', sa.VARCHAR(length=64), nullable=True),
    sa.Column('colonia_referencia_1', sa.VARCHAR(length=100), nullable=True),
    sa.Column('entidad_referencia_1', sa.VARCHAR(length=64), nullable=True),
    sa.Column('municipio_referencia_1', sa.VARCHAR(length=64), nullable=True),
    sa.Column('codigo_postal_referencia_1', sa.VARCHAR(length=10), nullable=True),
    sa.Column('apellido_paterno_referencia_2', sa.VARCHAR(length=100), nullable=True),
    sa.Column('apellido_materno_referencia_2', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telefono_celular_referencia_2', sa.VARCHAR(length=10), nullable=True),
    sa.Column('direccion_referencia_2', sa.VARCHAR(length=200), nullable=True),
    sa.Column('estado_referencia_2', sa.VARCHAR(length=64), nullable=True),
    sa.Column('colonia_referencia_2', sa.VARCHAR(length=100), nullable=True),
    sa.Column('entidad_referencia_2', sa.VARCHAR(length=64), nullable=True),
    sa.Column('municipio_referencia_2', sa.VARCHAR(length=64), nullable=True),
    sa.Column('codigo_postal_referencia_2', sa.VARCHAR(length=10), nullable=True),
    sa.Column('tipo_de_credito', sa.VARCHAR(length=50), nullable=True),
    sa.Column('banco', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notas_seguimiento', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('fecha_ultimo_contacto', sa.DATE(), nullable=True),
    sa.Column('fecha_siguiente_contacto', sa.DATE(), nullable=True),
    sa.Column('assigned_user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['user.id'], name='fk_client_assigned_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('team_leader_assignments',
    sa.Column('leader_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('leader_id', 'user_id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=64), nullable=False),
    sa.Column('apellido_paterno', sa.VARCHAR(length=64), nullable=False),
    sa.Column('apellido_materno', sa.VARCHAR(length=64), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('prototipo_imagenes')
    op.drop_table('prototipos')
    # ### end Alembic commands ###
