"""update_client_metadata_fields

Revision ID: b33abfeb88d1
Revises: 1c315840e5dd
Create Date: 2024-11-26 18:58:28.960823

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'b33abfeb88d1'
down_revision = '1c315840e5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Set default values for existing records
    conn.execute(sa.text(
        "UPDATE client SET "
        "fecha_registro = COALESCE(fecha_registro, CURRENT_TIMESTAMP), "
        "tipo = COALESCE(tipo, 'prospecto'), "
        "estatus = COALESCE(estatus, 'nuevo')"
    ))
    
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('fecha_registro',
               existing_type=sa.DATETIME(),
               nullable=False,
               server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               server_default='prospecto')
        batch_op.alter_column('estatus',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               server_default='nuevo')
        batch_op.drop_column('ultima_contacto')
        batch_op.drop_column('tipo_propiedad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_propiedad', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('ultima_contacto', sa.DATETIME(), nullable=True))
        batch_op.alter_column('estatus',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               server_default=None)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               server_default=None)
        batch_op.alter_column('fecha_registro',
               existing_type=sa.DATETIME(),
               nullable=True,
               server_default=None)

    # ### end Alembic commands ###
