"""remove sector field and reorder columns

Revision ID: c0ffa906b4a6
Revises: 115e20ee56d6
Create Date: 2024-11-26 20:16:22.667042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ffa906b4a6'
down_revision = '115e20ee56d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('sector')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
