"""Add tipo field to Client model

Revision ID: cc2aa163e2ff
Revises: 2b0e76206929
Create Date: 2024-11-26 17:29:29.708005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2aa163e2ff'
down_revision = '2b0e76206929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
