"""add seguimiento fields

Revision ID: d4a7c2e3f9a1
Revises: b8ed6a578df7
Create Date: 2024-11-26 22:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a7c2e3f9a1'
down_revision = 'b8ed6a578df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('client', schema=None) as batch_op:
            batch_op.add_column(sa.Column('notas_seguimiento', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('fecha_ultimo_contacto', sa.Date(), nullable=True))
            batch_op.add_column(sa.Column('fecha_siguiente_contacto', sa.Date(), nullable=True))
    except Exception as e:
        print(f"Error during migration: {e}")
        # If columns already exist, we can skip
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('fecha_siguiente_contacto')
        batch_op.drop_column('fecha_ultimo_contacto')
        batch_op.drop_column('notas_seguimiento')

    # ### end Alembic commands ###
