"""add seguimiento fields

Revision ID: e5a8c2f4d9b2
Revises: b8ed6a578df7
Create Date: 2024-11-26 22:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a8c2f4d9b2'
down_revision = 'b8ed6a578df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas_seguimiento', sa.Text(), server_default='', nullable=True))
        batch_op.add_column(sa.Column('fecha_ultimo_contacto', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_siguiente_contacto', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('fecha_siguiente_contacto')
        batch_op.drop_column('fecha_ultimo_contacto')
        batch_op.drop_column('notas_seguimiento')

    # ### end Alembic commands ###
