"""split_apellido_into_paterno_materno

Revision ID: febe15bdb8f2
Revises: b33abfeb88d1
Create Date: 2024-11-26 19:37:39.542445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febe15bdb8f2'
down_revision = 'b33abfeb88d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido_paterno', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('apellido_materno', sa.String(length=100), nullable=False))
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('apellido_materno')
        batch_op.drop_column('apellido_paterno')

    # ### end Alembic commands ###
